export const SHOW_SIGNUP_MODAL = 'MODAL/SHOW-SIGNUP-MODAL';
export const SHOW_SIGNIN_MODAL = 'MODAL/SHOW-SIGNIN-MODAL';
export const HIDE_MODAL = 'MODAL/HIDE-MODAL';

export const SET_CURRENT_USER = 'USER/SET-CURRENT-USER';
export const REMOVE_CURRENT_USER = 'USER/REMOVE-CURRENT-USER';

export const SET_COUPONS = 'COUPONS/SET-COUPONS';

export const SET_CATEGORIES = 'CATEGORIES/SET-CATEGORIES';
export const SET_CURRENT_CATEGORY = 'CATEGORIES/SET-CURRENT-CATEGORY';
